### ISSUE TITLE
A great, great issue.

### ISSUE THREAD

**Issue by Cedyk** [MUnique/OpenMU#146] opened 2020-01-16 18:36 UTC
Hello, it's me again, testing the server, this time I ran into some errors, and also with some doubts, and when researching the database, I found some things to modify, but others it was impossible. Here we go again..

PJ Errors:
~~- When creating the character "Dark Wizard", he does not have his basic ability (Energy Ball). As I researched in the "config.Skill" table, the "id # 47" is this skill. Which apparently is not added to the "data.SkillEntry" table.~~
~~- When creating a Dark Night, it does not have in its inventory its primary weapon (Small Axe).~~
~~- When creating an Elf, it does not have in its inventory its primary weapon (Short Bow & Arrow)~~
~~- Elves do not regenerate life automatically.~~  [issue #149](https://github.com/MUnique/OpenMU/issues/149)

Skills Errors
~~- When you buy in Lorencia "Scroll of Power Wave" and learn this skill, it does not work until you leave the client, and reconnect to the game.~~
~~- The following "Dark Wizard" skills, after buying and learning them, when trying to use them, the character performs the "mimic", but does NOT hurt, does NOT consume mana, and the animation of the skill is not shown:~~
~~- Lightining~~
~~- Meteorite~~
~~- Poison~~
~~- Teleport~~
~~- Twister~~
~~- Flame~~

Items errors:
~~- The arrows used are not subtracted from the total arrows (Elf).~~ [issue #4](https://github.com/MUnique/OpenMU/issues/4)
~~- Zen does not fall to the floor, it goes to inventory automatically. (In the previous issues, I think this error did not [occur)~~ [issue #116](https://github.com/MUnique/OpenMU/issues/116)
~~- Arcangel Scroll (+0) was the one I could test, it appears with zero "sale price". But by selling them, you get an amount of Zen (5000).~~ [issue #150](https://github.com/MUnique/OpenMU/issues/150)
- Mana potions are not automatically consumed from inventory, as are life potions, apples, etc.
~~- When you drop an item to the floor, it falls but remains in the inventory until reconnecting with that character.~~

```
[ERROR] 2020-01-16 15:13:43,955 [MUnique.OpenMU.GameLogic.DroppedItem] [(null)] - Error during DroppedItem.DisposeAndDelete
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at MUnique.OpenMU.Persistence.EntityFramework.EntityFrameworkContext.SaveChanges() in C:\Users\rolda\Desktop\OpenMU-master\src\Persistence\EntityFramework\EntityFrameworkContext.cs:line 59
   at MUnique.OpenMU.GameLogic.DroppedItem.DeleteItem(Player player) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\DroppedItem.cs:line 227
   at MUnique.OpenMU.GameLogic.DroppedItem.DisposeAndDelete(Object state) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\DroppedItem.cs:line 130
```

```
[ERROR] 2020-01-16 15:22:07,706 [MUnique.OpenMU.GameLogic.DroppedItem] [(null)] - Error during DroppedItem.DisposeAndDelete
System.InvalidOperationException: The instance of entity type 'ExitGate' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at MUnique.OpenMU.Persistence.EntityFramework.EntityFrameworkContext.Delete[T](T obj) in C:\Users\rolda\Desktop\OpenMU-master\src\Persistence\EntityFramework\EntityFrameworkContext.cs:line 115
   at MUnique.OpenMU.GameLogic.DroppedItem.DeleteItem(Player player) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\DroppedItem.cs:line 227
   at MUnique.OpenMU.GameLogic.DroppedItem.DisposeAndDelete(Object state) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\DroppedItem.cs:line 130
```

Maps errors:
- When you die in Devias or Noria, you are teleported to Lorencia.
- In noria, monsters do not drop Zen and items cannot be taken from the floor.

How I do it:
- How to set the amount of experience on the server.
- How to set the amount of items (drop) on the server.
- How to edit the amount of zen a character.
- How to edit a character. (The stats are hashed or encrypted).
- How to edit monster spots.

Suggestion:
- Character editor.
- Item editor.

**Comment by sven-n** [comment] 2020-01-16 18:48
Wow, thank you. I knew some of these issues exist - however, some features are just not implemented yet ;) You can find some of them in the existing issues.

I‘ll first work trough the exceptions as they‘re most critical. I think some of this got broken by updating .net core and entity framework core to 3.x :(

**Comment by sven-n** [comment] 2020-01-17 06:38
> When creating the character "Dark Wizard", he does not have his basic ability (Energy Ball). As I researched in the "config.Skill" table, the "id # 47" is this skill. Which apparently is not added to the "data.SkillEntry" table.
> When creating a Dark Night, it does not have in its inventory its primary weapon (Small Axe).
> When creating an Elf, it does not have in its inventory its primary weapon (Short Bow & Arrow)

The initialization of the inventory for new characters is not implemented yet.

> Elves do not regenerate life automatically.

Do you mean in the safezone? You're right, but this affects every character class. Also not implemented yet. However, with a ring, pendant etc. with recovery, it should work.

> Skills Errors

I need to check this, looks like a bug.

> The arrows used are not subtracted from the total arrows (Elf).

See #4.

> Zen does not fall to the floor, it goes to inventory automatically. (In the previous issues, I think this error did not occur)

See #116.
 
> Arcangel Scroll (+0) was the one I could test, it appears with zero "sale price". But by selling them, you get an amount of Zen (5000).

Will need to look into it.

> Mana potions are not automatically consumed from inventory, as are life potions, apples, etc.

That's strange, because actually the game client is responsible to send consumption messages to the Server. But maybe the server fails to consume an item.

> When you drop an item to the floor, it falls but remains in the inventory until reconnecting with that character.

Error :(

> When you die in Devias or Noria, you are teleported to Lorencia.

Yes, it's not implemented yet :-/

> In ferris wheel, monsters do not drop Zen and items cannot be taken from the floor.

What is the "ferris wheel"?


> How I do it:
> How to set the amount of experience on the server.
> How to set the amount of items (drop) on the server.
> How to edit the amount of zen a character.
> How to edit a character. (The stats are hashed or encrypted).
> How to edit monster spots.

Currently, there is no user interface to do that. You can edit all of this in the database.

Experience Rate: It's stored in the table ConstValueAttribute, which is defined for each character character class.
```
UPDATE config."ConstValueAttribute"
SET "Value" = 5
WHERE "DefinitionId" = '1AD454D4-BEF9-416E-BC49-82A5B0277FC7'
```

Drop rates: Table ```config."DropItemGroup"```

Zen of a Character: It's stored in the "ItemStore" (Inventory) of the character.
Example:
```
UPDATE data."ItemStorage"
SET "Money" = 1234567
WHERE "Id" = (SELECT "InventoryId"
				from data."Character"
				where "Name" = 'test300Dk');
```

The stats of a character: Well, you can see the stats here:
```
SELECT stat."Value", def."Designation", character."Name"
FROM data."StatAttribute" stat, config."AttributeDefinition" def, data."Character" character
WHERE stat."DefinitionId" = def."Id"
and stat."CharacterId" = character."Id"
```
To change it:
```
UPDATE data."StatAttribute"
SET "Value" = 3000
WHERE "DefinitionId" = '123282fe-fead-448e-ad2c-baece939b4b1' -- The id of the attribute, see below
AND "CharacterId" = (SELECT "Id"
				from data."Character"
				where "Name" = 'test300Dk')

-- Strength: '123282fe-fead-448e-ad2c-baece939b4b1'
-- Agility:  '1ae9c014-e3cd-4703-bd05-1b65f5f94ceb'
-- Vitality: '6ca5c3a6-b109-45a5-87a7-fdcb107b4982'
-- Energy:   '01b0ef28-f7a0-46b5-97ba-2b624a54cd75'
-- Command(DL):  '6af2c9df-3ae4-4721-8462-9a8ec7f56fe4'
```

Monster Spots: These are configured in the table config."MonsterSpawnArea".

> Suggestion:
Character editor.
Item editor.

It's definitely on my TODO list ;-)

**Comment by sven-n** [comment] 2020-01-19 10:31
> When you drop an item to the floor, it falls but remains in the inventory until reconnecting with that character.

Should be fixed. The server didn't send the correct message back about the success of the drop.

**Comment by sven-n** [comment] 2020-01-19 10:52
> Arcangel Scroll (+0) was the one I could test, it appears with zero "sale price". But by selling them, you get an amount of Zen (5000).

Did you get this from a monster drop? Because it shouldn't exist as +0 xD

**Comment by sven-n** [comment] 2020-01-20 06:14
> When you die in Devias or Noria, you are teleported to Lorencia.

Improved by the last commit.

**Comment by Cedyk** [comment] 2020-01-20 16:22
Sorry, I was somewhat away from the keyboard. I catch up now with your answers.

- When I try to edit the characteristics of a character, placing a number greater than 255, the value shown in the client is not correct. Is the value in bytes or something?

> What is the "ferris wheel"?
- Sorry, google translator, modified "NORIA" by "ferris whell".

> Did you get this from a monster drop? Because it shouldn't exist as +0 xD
- The item goes to from its base, which is 0 to: + 1, + 2, + 3, + 4, + 5. I was referring to the item in its base state.

PD: In a while I recompile and try the rest. Thank you so much for everything!

**Comment by sven-n** [comment] 2020-01-20 17:29
> When I try to edit the characteristics of a character, placing a number greater than 255, the value shown in the client is not correct. Is the value in bytes or something?

It was a wrong cast to byte. I fixed it :)

**Comment by sven-n** [comment] 2020-01-21 06:07
> Mana potions are not automatically consumed from inventory, as are life potions, apples, etc.

> When you buy in Lorencia "Scroll of Power Wave" and learn this skill, it does not work until you leave the client, and reconnect to the game.
The following "Dark Wizard" skills, after buying and learning them, when trying to use them, the character performs the "mimic", but does NOT hurt, does NOT consume mana, and the animation of the skill is not shown:
Lightining
Meteorite
Poison
Teleport
Twister
Flame

I can't reproduce these issue. It's just Teleport which is not implemented yet. Did it occur for you because of the unsuccessful item drop? Can you try if this issue is still a problem?

> The item goes to from its base, which is 0 to: + 1, + 2, + 3, + 4, + 5. I was referring to the item in its base state.

I think, these event items start by +1 for the corresponding Blood Castle level. It may be possible that the server drops them as +0, because I didn't implement a special logic to set a minimum item level.

> In Noria, items cannot be taken from the floor.

I can reproduce the issue, but I don't know yet what's the root of the issue. The game client requests to pick up the item with an id of 0, which obviously fails. Previously, the server sent the correct id to the client. In Lorencia, this works, so I don't know what I'm doing wrong :-(

**Comment by Cedyk** [comment] 2020-01-21 20:15
> I can't reproduce these issues. It's just Teleport which is not implemented yet. Did it occur for you because of the unsuccessful item drop? Can you try if this issue is still a problem?

1. Create a new character (Dark Wizard)
2. I bought the Skills Scrolls in the store.  (without Teleport)
3. I learned the skills, some do not work at first.
4. Some work after a while or under some condition that I don't know.

I hope this helps you to replicate the problem
PD: I will try to replicate the rest and if I can, I will do a step by step how to replicate it.

**Comment by Cedyk** [comment] 2020-01-21 21:26
> When you drop an item to the floor, it falls but remains in the inventory until reconnecting with that character.

> Should be fixed. The server didn't send the correct message back about the success of the drop.

When the items on the floor disappear, it throws the following error:
```
[ERROR] 2020-01-21 17:23:39,093 [MUnique.OpenMU.GameLogic.DroppedItem] [(null)] - Error during DroppedItem.DisposeAndDelete
System.InvalidOperationException: The instance of entity type 'ExitGate' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at MUnique.OpenMU.Persistence.EntityFramework.EntityFrameworkContext.Delete[T](T obj) in C:\Users\rolda\Desktop\OpenMU-master\src\Persistence\EntityFramework\EntityFrameworkContext.cs:line 115
   at MUnique.OpenMU.GameLogic.DroppedItem.DeleteItem(Player player) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\DroppedItem.cs:line 226
   at MUnique.OpenMU.GameLogic.DroppedItem.DisposeAndDelete(Object state) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\DroppedItem.cs:line 130
```

**Comment by sven-n** [comment] 2020-01-22 18:37
> When creating the character "Dark Wizard", he does not have his basic ability (Energy Ball). As I researched in the "config.Skill" table, the "id # 47" is this skill. Which apparently is not added to the "data.SkillEntry" table.
> When creating a Dark Night, it does not have in its inventory its primary weapon (Small Axe).
> When creating an Elf, it does not have in its inventory its primary weapon (Short Bow & Arrow)

All fixed :)


> When the items on the floor disappear, it throws the following error:

I found it out... will need to think a bit how I fix it.

**Comment by Cedyk** [comment] 2020-01-22 22:30
Great! I just recompiled and tried everything. Fortunately, the arrangements work well. I touched on the main issue the things that were already resolved.

Seeing the last commit (https://github.com/MUnique/OpenMU/commit/54885c12f9a9c57914d75689ba1623c15fcb6f2c) I realized that Dark Wizard's skills have a requirement level. Perhaps it is for this reason that spells can be learned but cannot be used until reaching that level.

Another thing I have noticed with Energy Ball, is that it does not consume mana. I don't know if the same happens with the rest of the spells.

**Comment by sven-n** [comment] 2020-01-23 06:04
> Seeing the last commit (54885c1) I realized that Dark Wizard's skills have a requirement level. Perhaps it is for this reason that spells can be learned but cannot be used until reaching that level.

You're right… Most of these skills shouldn't have a level requirement. They require just a certain amount of energy.

**Comment by sven-n** [comment] 2020-01-23 06:42
The dropped item cleanup and the skill requirements have been fixed with my latest commits.

**Comment by sven-n** [comment] 2020-01-24 06:09
> The dropped item cleanup and the skill requirements have been fixed with my latest commits.

I just noticed, the scroll requirements (to learn the skills), are also wrong. My data which I used as a base wasn't very good, I guess ;)

**Comment by sven-n** [comment] 2020-01-24 06:48
> I just noticed, the scroll requirements (to learn the skills), are also wrong. My data which I used as a base wasn't very good, I guess ;)

Improved with last commit :)


>> Elves do not regenerate life automatically.

>Do you mean in the safezone? You're right, but this affects every character class. Also not implemented yet. However, with a ring, pendant etc. with recovery, it should work.

Added issue #149

**Comment by sven-n** [comment] 2020-01-24 20:10
>> Arcangel Scroll (+0) was the one I could test, it appears with zero "sale price". But by selling them, you get an amount of Zen (5000).

> Did you get this from a monster drop? Because it shouldn't exist as +0 xD

Created issue #150 for that

**Comment by sven-n** [comment] 2020-02-17 06:23
> In noria, [...] items cannot be taken from the floor.

@fos83 gave me a hint. When he removed some monsters from the map, he could pick up items again. I think the root of the issue is the way how the IDs for drops are handled. For the sake of simplicity, there is one dictionary and one id sequence for all kind of objects on a GameMap. That means, Players, NPCs, Monsters, Drops all have a unique id. However, in the original server, drops have their own id sequence. I assume, the problem here is, that new drops get an id which is too high for the game client. The game client seems to have a hard limit about drop ids.

The easiest solution would be to add a second dictionary and a second id sequence to the GameMap. I'll think about a more elegant solution, though.

**Comment by sven-n** [comment] 2020-02-18 18:50
> The easiest solution would be to add a second dictionary and a second id sequence to the GameMap. I'll think about a more elegant solution, though.

I did a bit of research and found out that the original server is only capable of holding 300 dropped items/zen on the ground at the same time. When more stuff is about to drop, it just doesn't drop. 

So, to fix our issue here, I suggest to reserve the first few hundred (maybe 512? :)) IDs for drops and the following for the other objects (Players, Monsters, etc.).

**Comment by sven-n** [comment] 2020-02-19 06:39
Fixed the noria bug.

> Mana potions are not automatically consumed from inventory, as are life potions, apples, etc.

Can you explain this in detail? I found no issue :( Mana potions are automatically consumed by the client when mana is too low to execute a requested skill. Health potions are not automatically consumed. The player needs to trigger that manually, e.g. by using a shortcut key.

**Comment by sven-n** [comment] 2020-03-14 20:43
I'll close this for now. If anything is not yet handled in another issue, please create a new issue for each problem :)

**Closed by sven-n** 2020-03-14 20:43 UTC

**Comment by sven-n** [comment] 2020-04-03 12:34
>>  Mana potions are not automatically consumed from inventory, as are life potions, apples, etc.

> Can you explain this in detail? I found no issue :( Mana potions are automatically consumed by the client when mana is too low to execute a requested skill. Health potions are not automatically consumed. The player needs to trigger that manually, e.g. by using a shortcut key.

Sorry! I encountered the same problem and realized it's the problem you described. I fixed it at master. There was simply no mana update sent from server to client when doing a skill :-(
