### ISSUE TITLE
Progress lost BUG

### ISSUE THREAD

**Issue by GabrielPedrico** [MUnique/OpenMU#261] opened 2022-06-08 18:11 UTC
**Describe the bug**
Sometimes when the player is unexpectedly disconnected all of its progress is being lost.

**To Reproduce**
1. Make some progress.
2. Disconnect in an unconventional way (not using the in-game interface)
4.  reconnects and see the error your progress your progress will probably not be saved.

**Expected behavior**
My progress is saved with level attributes and items obtained during the journey

**Additional context**
Client 1.04d

![image](https://user-images.githubusercontent.com/61802922/172687264-79540923-1672-4129-925e-a31ac39393ce.png)

**Comment by sven-n** [comment] 2022-06-20 10:13
I can't reproduce the issue in a simple way :-( However, I know it is there - I noticed it maybe one or two times as well in the past.

Can you give me more precise steps to reproduce? Do you know any specific action which leads to the problem?

**Comment by sven-n** [comment] 2022-10-21 16:35
I just found a way to reproduce the issue with these steps:
- log in to test account test300
- choose the dark wizard
- go to the NPC 'Pasi the Mage' and buy a teleport skill scroll
- learn the skill by right clicking the scroll
- Esc -> Select Server

**Comment by sven-n** [comment] 2022-10-21 17:42
Since I probably found the root of the cause, I'm closing this issue for now. Please notify me, if you ever encounter it again.

**Closed by sven-n** 2022-10-21 17:42 UTC
Labels: bug
